#ifndef POWERUP_DEFAULT_VALUE_H
#define POWERUP_DEFAULT_VALUE_H

enum powerupVarEnum
{
	VAR_BOOT_OPTI = 0,
	VAR_NUM_OF_VAR,
	VAR_DEFA_DO,
	VAR_DEFA_IP,
	VAR_DEFA_NET_MASK,
	VAR_DEFA_GATE_WAY,
	VAR_BOOT_OPTI_ADDR,
	VAR_MOTOR_ID_INV,
	VAR_CIPHER_TXT_0,
	VAR_CIPHER_TXT_1,
	VAR_CIPHER_TXT_2,
	VarNum
};


#endif
//end of file
